bet/urls.py
from django.urls import path

from . import views

app_name = 'bet'

urlpatterns = [
    path('', views.index, name='index'),
    path('faq/<int:tema_pk>', views.faq_view, name='faq'),

    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),

    path('profile/<page>', views.profile_view, name="profile"),
    path('request/vip', views.request_vip, name="request-vip"),

    path('email/confirmation/<uidb64>/<token>', views.email_confirmation, name='email-confirmation'),
    path('email/resend/link/', views.resend_link_confirmation, name='resend-confirmation'),

    path('pagamento/<int:product_pk>', views.pagamento_page, name="pagamento"),
    path('pagamento/session-id', views.sessionID, name='pagseguro-session-id'),
]

betsite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bet.urls', namespace='bet')),
    path('social-auth/',include('social_django.urls', namespace='social')),


    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="bet/accounts/reset_password.html",
                                                                subject_template_name="bet/emails/subject.txt",
                                                                email_template_name="bet/emails/password_reset_email.html"), name="password_reset"),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="bet/accounts/reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="bet/accounts/reset_confirm.html"), name="password_reset_confirm"),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name="bet/accounts/reset_complete.html"), name="password_reset_complete"),

    path('retorno/pagseguro', include('pagseguro.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bet/models.py
from django.contrib.auth.models import AbstractUser
from simple_email_confirmation.models import SimpleEmailConfirmationUserMixin
from pagseguro.signals import notificacao_recebida
from django.db import models

from .validators import CustomASCIIUsernameValidator
from .managers import ProductPurchase, VipRequestManager

# Create your models here.

class FaqTemas(models.Model):
    choice = models.CharField(max_length=100)

    def __str__(self):
        return "{}".format(self.choice)

    
class Faq(models.Model):
    pergunta = models.CharField(max_length=80)
    resposta = models.TextField(max_length=100)
    tema = models.ForeignKey(FaqTemas, on_delete=models.CASCADE)


class CustomUser(SimpleEmailConfirmationUserMixin, AbstractUser):
    email = models.EmailField(unique=True,max_length=255)
    first_name = models.CharField(max_length=80)
    last_name = models.CharField(max_length=80)
    phone = models.CharField(max_length=16, blank=True)

    def __init__(self, *args, **kwargs):
        self._meta.get_field(
            'username'
        ).validators[0] = CustomASCIIUsernameValidator()

        super().__init__(*args, **kwargs)


class Produtos(models.Model):
    nome = models.CharField(max_length=50)
    preco = models.FloatField()
    preco_text = models.CharField(max_length=20)
    descricao = models.TextField(max_length=300)
    pagseguro = models.BooleanField(default=True)

    def __str__(self):
        return self.nome


class UserProdutos(models.Model):
    user = models.ForeignKey(CustomUser,
                                on_delete=models.CASCADE)
    produto = models.ForeignKey(Produtos,
                                on_delete=models.CASCADE)
    vip_expiration = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=10, default="aguardando")
    checkout = models.CharField(max_length=36, unique=True)
    objects = ProductPurchase()

    def __str__(self):
        return "{} - {}".format(self.produto.nome, self.user.username)


class VipRequest(models.Model):
    purchase = models.ForeignKey(UserProdutos,
                                on_delete=models.CASCADE)
    added = models.BooleanField(default=False)
    objects = VipRequestManager()


class Depoimentos(models.Model):
    nome_pessoa = models.CharField(max_length=50)
    foto = models.ImageField(upload_to="depoimentos-pics/")
    video_link = models.CharField(max_length=50)
    

def update_purchase(sender, transaction, **kwargs):
    purchase = UserProdutos.objects.update_purchase(transaction)
    
    if transaction['status'] == '3' and purchase:
        VipRequest.objects.requestVip(purchase)

notificacao_recebida.connect(update_purchase)

bet/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django import forms
from .models import CustomUser

class CreateUserForm(UserCreationForm):
    error_messages = {
        'password_mismatch': "Senhas não coincidem",
    }
    phone = forms.CharField(max_length=16)

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        campos = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'phone']
        
        for campo in campos:
            self.fields[campo].widget.attrs['class'] = 'form-control'
            self.fields[campo].widget.attrs['id'] = 'input'+campo.capitalize()
        
        self.fields['first_name'].widget.attrs['autofocus'] = 'autofocus'

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'phone']
        error_messages = {
            'username':{
                'unique': 'Esse usuário já existe.',
            },
            'email':{
                'unique': 'Esse email já existe.'
            }
        }

class LoginForm(forms.Form):
    widgets = {
        'email': forms.TextInput(attrs={
            'class':'form-control',
            'placeholder':'Email address',
            'name': 'username',
            'autofocus':True,
        }),
        'password': forms.PasswordInput(attrs={
            'class':'form-control',
            'placeholder':'Senha',
            'name': 'password',
        }),
    }

    inputEmail = forms.CharField(label="User/Email", widget=widgets['email'])
    inputPassword = forms.CharField(label="Senha", widget=widgets['password'])
    

class UpdateProfile(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name', 'phone')
        error_messages = {
            'username':{
                'unique': 'Esse usuário já existe.',
            },
            'email':{
                'unique': 'Esse email já existe.'
            }
        }

        
    def clean_email(self):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')

        if email and CustomUser.objects.filter(email=email).exclude(username=self.instance.username).count():
            raise forms.ValidationError('This email address is already in use. Please supply a different email address.')

        return email

bet/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeForm
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.db.models import Count
from django.contrib.sites.shortcuts import get_current_site
from django.utils.functional import SimpleLazyObject
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from urllib.parse import urlencode

from collections import Counter
from datetime import datetime
import json
import re

from simple_email_confirmation.models import EmailAddress
from pagseguro.api import PagSeguroApiTransparent

from .forms import CreateUserForm, LoginForm, UpdateProfile
from .models import *

CONTACT_EMAIL_MESSAGE = "Email enviado por {}, através do email {}\n\n{}"

def index(request):
    depoimentos = Depoimentos.objects.all()
    products = Produtos.objects.all()
    faq_tema = FaqTemas.objects.all().first()

    context =  {
        'site': request.site,
        'faq_tema': faq_tema,
        'depoimentos': depoimentos,
        'products': products,
        'resended': request.GET.get('resended'),
        'succes_message': True,
    }

    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = CONTACT_EMAIL_MESSAGE.format(name, email, request.POST.get('message'))
        
        send_mail(subject=subject, message=message, from_email=email, recipient_list=[settings.EMAIL_HOST_USER])
        messages.success(request, 'Email de contato enviado.')

    elif request.user.is_authenticated and bool(EmailAddress.objects.filter(user__pk=request.user.pk, confirmed_at=None)):
        if not context['resended']:
            context['success_message'] = False
            for message in messages.get_messages(request):
                if "confirmation_request" in message.tags:
                    return render(request, 'bet/home/index.html', context=context)

            print("MAARAVILAH",messages.get_messages(request))
            messages.warning(request, 'Seu email não está confirmado, por favor confirme acessando link que mandamos em seu email.')
        else:
            context['success_message'] = True
            messages.warning(request, 'Link de confirmação enviado.')

    return render(request, 'bet/home/index.html', context=context)

def faq_view(request, tema_pk):
    perguntas = Faq.objects.filter(tema__pk=tema_pk).values('pergunta', 'resposta')
    temas = FaqTemas.objects.annotate(number_of_questions=Count('faq'))

    return render(request, 'bet/faq/faq-perguntas.html', {
        'perguntas': perguntas,
        'temas': temas,
        'id': tema_pk,
    })

def login_view(request):
    if request.user.is_authenticated:
        return redirect('bet:index')

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST.get('inputEmail')
            password = request.POST.get('inputPassword')

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                if not request.GET.get('next'):
                    return redirect('bet:profile', page="infos")
                else:
                    return HttpResponseRedirect(request.GET.get('next'))
            else:
                messages.info(request, "usuário/email ou senha incorretos")

    form = LoginForm(auto_id="%s")
    return render(request, 'bet/accounts/login.html', context={'form':form})

def logout_view(request):
    logout(request)
    return redirect('bet:index')

def register(request):
    if request.user.is_authenticated:
        return redirect('bet:index')

    form = CreateUserForm()
    
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            
            send_confirmation_link(user, request.site)

            return redirect('bet:login')
        else:
            for msgs in form.errors.as_data().values():
                for msg in msgs:
                    messages.error(request, *msg)

    return render(request, 'bet/accounts/register.html', {'form': form})

def change_pass(request):
    form = PasswordChangeForm(user=request.user, data=request.POST)

    if form.is_valid():
        form.save()
        update_session_auth_hash(request, form.user)
        messages.success(request,"Senha alterada.")
    else:
        errors = json.loads(form.errors.as_json())
        
        for error_field, error_list in errors.items():
            code = error_list[0]['code']
            if code == 'password_mismatch':
                messages.error(request,'Senhas não coincidem')
            elif code == 'password_incorrect':
                messages.error(request,'Senha atual incorreta.')
            else:
                messages.error(request,error_list[0]['message'])

def change_infos(request):
    old_email = request.user.email
    form = UpdateProfile(request.POST, instance=request.user)

    if form.is_valid():
        form.save()

        if old_email != request.POST.get('email'):
            EmailAddress.objects.filter(user=request.user).delete()
            send_confirmation_link(request.user, request.site)

            messages.success(request, "Alterado com sucesso! Confirme seu email por meio do link que mandamos.")
        else:
            messages.success(request, "Alterado com sucesso!")

    else:
        errors = json.loads(form.errors.as_json())
        print(errors)
        for error in errors.values():
            message = error[0]['message']
            if 'This email address is already in use' in message:
                message = "Esse email já está cadastrado."

            messages.error(request, message)

@login_required(login_url="bet:login")
def profile_view(request, page):
    context = {
        'page': page,
        'has_vip': UserProdutos.objects.filter(user=request.user, vip_expiration__gte=datetime.now()).count(),
    }
    
    if page == "infos":
        context['form'] = UpdateProfile()

    elif page == "planos":
        try:
            context['expiration'] = UserProdutos.objects.filter(user=request.user).order_by('vip_expiration').last().vip_expiration.date()
        except AttributeError:
            context['expiration'] = "Não contratado"

    if request.method == 'POST':
        if page == "password":
            change_pass(request)

        elif page == "infos":
            change_infos(request)
            return redirect("bet:profile", page="infos")

    return render(request, "bet/accounts/profile-%s.html"%(page), context=context)

@login_required(login_url="bet:login")
def request_vip(request):
    purchase = UserProdutos.objects.filter(user=request.user, vip_expiration__gte=datetime.now(), status="pago").order_by('vip_expiration').last()

    if purchase:
        vip_req = VipRequest.objects.requestVip(purchase)
        vip_req.added = False
        vip_req.save()

        messages.success(request, "Já solicitamos a sua entrada ao grupo, iremos verificar os dados.")

    else:
        messages.warning(request, "Você não possui esse plano. Gostaria de contratar? ")

    return redirect("bet:profile", page="planos")

@login_required(login_url="bet:login")
def request_curso(request):
    has_course = UserProdutos.objects.filter(user=request.user, produto__pk=2, status="pago").count()

    if has_course:
        message = "Olá {}, aqui está o link do nosso curso.\n\n{}\n\nTenha um bom aprendizado!\n atenciosamente hackeandoabanca.".format(request.user.first_name,"https://google.com")
        send_mail(subject="Solicitação do link do curso", message=message, from_email=settings.EMAIL_HOST_USER, recipient_list=[request.user.email])

        messages.success(request, "Enviamos o link para o seu email.")

    else:
        messages.warning(request, "Você não possui esse plano. Gostaria de contratar? ")

    return redirect("bet:profile", page="planos")

@login_required(login_url="bet:login")
def pagamento_page(request, product_pk):
    
    if not bool(EmailAddress.objects.filter(user__pk=request.user.pk, confirmed_at=None)):
        produto = Produtos.objects.get(pk=product_pk)

        if request.method == 'POST':
            data = UserProdutos.objects.create_checkout(request, produto)
            print("DATA")
            print(data)
            if data['status_code'] != 200:
                messages.warning(request, "Existem campos inválidos. Por favor tente novamente")
                return redirect("bet:pagamento", product_pk=product_pk)
            try:
                link_boleto = data['transaction']['paymentLink']
                message = "Olá {}, aqui está o boleto para o pagamento do plano.\nAgradecemos sua compra. {}".format(
                    request.user.first_name, request.site.name)
                send_mail("Boleto de pagamento", message, from_email=settings.EMAIL_HOST_USER, recipient_list=[request.user.email,])

            except KeyError:
                pass


bet/templates/bet/accounts/account_activation.html
{% extends "bet/base.html" %}
{% load static %}

{% block css_links %}
<style>
    body {
  padding-top: 5rem;
}
.starter-template {
  padding: 3rem 1.5rem;
}
.navbar-brand{
    padding-left: 8%;
}
</style>
{% endblock %}

{% block content %}

  {% include "bet/simple_nav.html" %}
  
  <main role="main" class="container">

    <div class="starter-template">
      <h1>{{titulo}}</h1>
      <p class="lead">{{info}}</p>
        <a href="{% url link %}">{{link_text}}</a>
    </div>

  </main>
{% endblock %}

bet/templates/bet/accounts/login.html
{% extends 'bet/base.html' %}
{% load static %}

{% block css_links %}
<link rel="stylesheet" href="{% static "css/accounts.css" %}">
{% endblock %}

{% block content %}
<div class="container">
<div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
    <div class="card card-signin my-5">
        <div class="card-body">
        <h5 class="card-title text-center">Entre</h5>
        <form class="form-signin" method='POST'>
            {% csrf_token %}
            <div class="form-label-group">
            <!-- <input name="inputEmail" type="text" id="inputEmail" class="form-control" placeholder="Email address" required autofocus> -->
            {{form.inputEmail}}
            <label for="{{form.inputEmail.id_for_label}}">User/Email</label>
            </div>

            <div class="form-label-group">
            <!-- <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Senha" required> -->
            {{form.inputPassword}}
            <label for="{{form.inputPassword.id_for_label}}">Senha</label>
            </div>

            <!--<div class="custom-control custom-checkbox mb-3">
            <input type="checkbox" class="custom-control-input" id="customCheck1">
            <label class="custom-control-label" for="customCheck1">Remember password</label>
            </div>-->
            <button class="btn-submit btn btn-lg btn-block text-uppercase" type="submit">Entre</button>
            <div class="mt-2">
                <div class="d-flex justify-content-center links">
                    Não tem conta? <a href="{% url "bet:register" %}" class="ml-2">cadastre-se</a>
                </div>
                <div class="d-flex justify-content-center links">
                    Esqueceu a senha? <a href="{% url "password_reset" %}" class="ml-2">Resetar senha</a>
                </div>
            </div>
            {% if messages %}
                <div class="mt-3"></div>
                {% for message in messages %}
                    <div class='alert alert-danger'>{{ message }}</div>
                {% endfor %}
            {% endif %}
            <hr class="my-4">
            <a class="btn btn-lg btn-google btn-block text-uppercase" href="{% url "social:begin" "google-oauth2" %}"><i class="fab fa-google mr-2"></i> Entre com Google</a>
            <a class="btn btn-lg btn-facebook btn-block text-uppercase" href="{% url "social:begin" "facebook" %}"><i class="fab fa-facebook-f mr-2"></i> Entre com Facebook</a>
        </form>
        </div>
    </div>
    </div>
</div>
</div>
{% endblock %}

bet/templates/bet/accounts/profile-infos.html
{% extends "bet/accounts/profile.html" %}
{% load static %}

{% block profile-content %}
<div class="col-lg-8">
    <!-- .card -->
    {% include "bet/accounts/profile-vip-message.html" %}

    <div class="card card-fluid">
      <h6 class="card-header"> Account </h6>
      <!-- .card-body -->
      <div class="card-body">
        {% for message in messages %}
        <div class="text-center alert {% if message.tags != "success" %}alert-danger{% else %} alert-success{% endif %} alert-dismissible fade show" role="alert">
            {{message}}
            
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        <!-- form -->
        <form method="post">
          {% csrf_token %}
          <!-- form row -->
          <div class="form-row">
            <!-- form column -->
            <div class="col-md-6 mb-3">
              <label for="input01">Nome</label>
              <input type="text" class="form-control" value="{{user.first_name}}" name="first_name" maxlength="80" required id="id_first_name"> </div>
            <!-- /form column -->
            <!-- form column -->
            <div class="col-md-6 mb-3">
              <label for="input02">Sobrenome</label>
              <input type="text" class="form-control" value="{{user.last_name}}" name="last_name" maxlength="80" required id="id_last_name"> </div>
            <!-- /form column -->
          </div>
          <!-- /form row -->
          <!-- .form-group -->
          <div class="form-group">
            <label for="input03">Email</label>
            <input class="form-control" value="{{user.email}}" type="email" name="email" maxlength="255" required id="id_email"> </div>
          <!-- /.form-group -->
          <!-- .form-group -->
          <div class="form-row">
            <div class="col">
              <label for="input05">Username</label>
              <input class="form-control" value="{{user.username}}" type="text" name="username" maxlength="150" required id="id_username">
            </div>
            <div class="col">
              <label for="input05">Phone</label>
              <input type="text" class="form-control" value="{{user.phone}}" name="phone" maxlength="16" id="id_phone">
            </div>
          </div>
          <!-- /.form-group -->
          <hr>
          <!-- .form-actions -->
          <div class="d-flex form-actions">
            <!-- enable submit btn when user type their current password -->
              <button type="submit" class="ml-auto btn update">Alterar Dados</button>
          </div>
          <!-- /.form-actions -->
        </form>
        <!-- /form -->
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
  <!-- /grid column -->
{% endblock %}

{% block profile_scripts %}
  <script src="{% static "libraries/jquery/jquery.mask.min.js" %}"></script>
  <script>
    $("#id_phone").mask('(00) 00000-0000');
  </script>
{% endblock %}

bet/templates/bet/accounts/profile-password.html
{% extends "bet/accounts/profile.html" %}

{% block profile-content %}
<div class="col-lg-8">
  {% include "bet/accounts/profile-vip-message.html" %}

    <!-- .card -->
    <div class="card card-fluid">
      <h6 class="card-header"> Mudar Senha </h6>
      <!-- .card-body -->
      <div class="card-body">
        {% for message in messages %}
        <div class="text-center alert {% if message.tags != "success" %}alert-danger{% else %} alert-success{% endif %} alert-dismissible fade show" role="alert">
            {{message}}
            
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        <!-- form -->
        <form method="post">
            {% csrf_token %}
          <!-- form row -->
          <div class="form-row">
            <!-- form column -->
            <div class="col-md-6 mb-3">
              <label for="id_new_password1">Nova senha</label>
              <input type="password" class="form-control" id="id_new_password1" autocomplete="new-password" name="new_password1" required=""> </div>

            <!-- /form column -->
          </div>

          <div class="form-row">
            <!-- form column -->
            <div class="col-md-6 mb-3">
              <label for="id_new_password2">Confirme a senha</label>
              <input type="password" class="form-control" name="new_password2" id="id_new_password2" autocomplete="new-password" required=""> </div>
            <!-- /form column -->
          </div>
          <!-- /.form-group -->
          <hr>
          <!-- .form-actions -->
          <div class="form-actions">
            <!-- enable submit btn when user type their current password -->
            <input type="password" name="old_password" autocomplete="off" class="form-control ml-auto mr-3" id="id_old_password" placeholder="Senha atual" required="">
            <button type="submit" class="btn update">Alterar senha</button>
          </div>
          <!-- /.form-actions -->
        </form>
        <!-- /form -->
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
  <!-- /grid column -->
  </div>
  {% endblock %}

bet/templates/bet/accounts/profile-planos.html
{% extends "bet/accounts/profile.html" %}

{% block profile-content %}
<div class="col-lg-8">
    <!-- .card -->
    {% include "bet/accounts/profile-vip-message.html" %}

    <div class="card card-fluid">
      <h6 class="card-header"> Planos </h6>
      <!-- .card-body -->
      <div class="card-body">
        {% for message in messages %}
          <div class="text-center alert {% if message.tags != 'success' %}alert-danger{% else %}alert-success{% endif %} alert-dismissible fade show" role="alert">
              {{message}} {% if message.tags == "warning" %}<a href="/#planos" class="alert-link">Planos</a>{% endif %}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
          </div>
        {% endfor %}
        <!-- form -->
        <form method="post">
            {% csrf_token %}
          <!-- form row -->
          <div class="row ">
            <div class="col"></div>
            <div class="col text-center py-4 px-5 rounded" style="background-color: #27ae60; color: white;">
                Expiração do VIP <br>
                {{expiration}}
            </div>
            <div class="col"></div>
          </div>

          <hr>
          <div class="row mb-2">
              <div class="col">
                  Mudou de número no telegram? <a href="{% url "bet:request-vip" %}">Requisite novo acesso ao vip</a>
              </div>
              <!-- <a class="btn btn-success btn-lg btn-block">VIP</a> -->
            <!-- /form column -->
          </div>
          <!-- /.form-group -->
          <!-- /.form-actions -->
        </form>
        <!-- /form -->
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
  <!-- /grid column -->
  </div>
  {% endblock %}

bet/templates/bet/accounts/profile-vip-message.html
{% if not request.user.phone and has_vip %}
    <div class="text-center alert alert-danger alert-dismissible fade show" role="alert">
      Coloque um número de celular. Usaremos ele para adicioná-lo ao nosso canal VIP do telegram
      
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
    </div>
{% endif %}

bet/templates/bet/accounts/reset_complete.html
{% extends "bet/base.html" %}
{% load static %}

{% block css_links %}
<style>
    body {
  padding-top: 5rem;
}
.starter-template {
  padding: 3rem 1.5rem;
}
.navbar-brand{
    padding-left: 8%;
}
</style>
{% endblock %}

{% block content %}
  {% include "bet/simple_nav.html" %}

  <main role="main" class="container">

    <div class="starter-template">
      <h3>Mudança de senha completa.</h3>
      <p class="lead">Sua senha foi mudada. Você pode fazer login com sua nova senha.</p>
      <a href="{% url "bet:login" %}">Log in</a>
    </div>

  </main>
{% endblock %}

bet/templates/bet/accounts/reset_password.html
{% extends "bet/base.html" %}
{% load static %}

{% block css_links %}
<link rel="stylesheet" href="{% static "css/accounts.css" %}">
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
            <div class="card-body">
            <div class="text-center">
                <h3><i class="fa fa-lock fa-4x"></i></h3>
                <h2 class="text-center">Esqueceu a senha?</h2>
                <p>Você pode resetar sua senha aqui.</p>
            </div>
            <form class="form-reset" method='POST'>
                {% csrf_token %}
                <div class="form-label-group">
                {{form.email}}
                <label for="id_email">Email</label>
                </div>

                <button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit">Reset</button>
                
            </form>
            </div>
        </div>
        </div>
    </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    input_obj = document.getElementById("id_email");

    input_obj.classList.add("form-control");
    input_obj.placeholder = "Email";
</script>
{% endblock %}

bet/templates/bet/accounts/reset_sent.html
{% extends "bet/base.html" %}
{% load static %}

{% block css_links %}
<style>
    body {
  padding-top: 5rem;
}
.starter-template {
  padding: 3rem 1.5rem;
}
.navbar-brand{
    padding-left: 8%;
}
</style>
{% endblock %}

{% block content %}
  {% include "bet/simple_nav.html" %}

  <main role="main" class="container">

    <div class="starter-template">
      <h1>Email de modificação enviado.</h1>
      <p class="lead">Nós enviamos para você instruções para modificar sua senha. Não esqueça de checar sua caixa de spam.<br> Se você não tiver recebido o email por favor certifique-se que você forneceu o email que você usou para se cadastrar.</p>
    </div>

  </main>
{% endblock %}