bet/urls.py
from django.urls import path

from . import views

app_name = 'bet'

urlpatterns = [
    path('', views.index, name='index'),
    path('faq/<int:tema_pk>', views.faq_view, name='faq'),

    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),

    path('profile/<page>', views.profile_view, name="profile"),
    path('request/vip', views.request_vip, name="request-vip"),

    path('email/confirmation/<uidb64>/<token>', views.email_confirmation, name='email-confirmation'),
    path('email/resend/link/', views.resend_link_confirmation, name='resend-confirmation'),

    path('pagamento/<int:product_pk>', views.pagamento_page, name="pagamento"),
    path('pagamento/session-id', views.sessionID, name='pagseguro-session-id'),
]

betsite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bet.urls', namespace='bet')),
    path('social-auth/',include('social_django.urls', namespace='social')),


    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="bet/accounts/reset_password.html",
                                                                subject_template_name="bet/emails/subject.txt",
                                                                email_template_name="bet/emails/password_reset_email.html"), name="password_reset"),
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="bet/accounts/reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="bet/accounts/reset_confirm.html"), name="password_reset_confirm"),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name="bet/accounts/reset_complete.html"), name="password_reset_complete"),

    path('retorno/pagseguro', include('pagseguro.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bet/models.py
from django.contrib.auth.models import AbstractUser
from simple_email_confirmation.models import SimpleEmailConfirmationUserMixin
from pagseguro.signals import notificacao_recebida
from django.db import models

from .validators import CustomASCIIUsernameValidator
from .managers import ProductPurchase, VipRequestManager

# Create your models here.

class FaqTemas(models.Model):
    choice = models.CharField(max_length=100)

    def __str__(self):
        return "{}".format(self.choice)

    
class Faq(models.Model):
    pergunta = models.CharField(max_length=80)
    resposta = models.TextField(max_length=100)
    tema = models.ForeignKey(FaqTemas, on_delete=models.CASCADE)


class CustomUser(SimpleEmailConfirmationUserMixin, AbstractUser):
    email = models.EmailField(unique=True,max_length=255)
    first_name = models.CharField(max_length=80)
    last_name = models.CharField(max_length=80)
    phone = models.CharField(max_length=16, blank=True)

    def __init__(self, *args, **kwargs):
        self._meta.get_field(
            'username'
        ).validators[0] = CustomASCIIUsernameValidator()

        super().__init__(*args, **kwargs)


class Produtos(models.Model):
    nome = models.CharField(max_length=50)
    preco = models.FloatField()
    preco_text = models.CharField(max_length=20)
    descricao = models.TextField(max_length=300)
    pagseguro = models.BooleanField(default=True)

    def __str__(self):
        return self.nome


class UserProdutos(models.Model):
    user = models.ForeignKey(CustomUser,
                                on_delete=models.CASCADE)
    produto = models.ForeignKey(Produtos,
                                on_delete=models.CASCADE)
    vip_expiration = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=10, default="aguardando")
    checkout = models.CharField(max_length=36, unique=True)
    objects = ProductPurchase()

    def __str__(self):
        return "{} - {}".format(self.produto.nome, self.user.username)


class VipRequest(models.Model):
    purchase = models.ForeignKey(UserProdutos,
                                on_delete=models.CASCADE)
    added = models.BooleanField(default=False)
    objects = VipRequestManager()


class Depoimentos(models.Model):
    nome_pessoa = models.CharField(max_length=50)
    foto = models.ImageField(upload_to="depoimentos-pics/")
    video_link = models.CharField(max_length=50)
    

def update_purchase(sender, transaction, **kwargs):
    purchase = UserProdutos.objects.update_purchase(transaction)
    
    if transaction['status'] == '3' and purchase:
        VipRequest.objects.requestVip(purchase)

notificacao_recebida.connect(update_purchase)

bet/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django import forms
from .models import CustomUser

class CreateUserForm(UserCreationForm):
    error_messages = {
        'password_mismatch': "Senhas não coincidem",
    }
    phone = forms.CharField(max_length=16)

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        campos = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'phone']
        
        for campo in campos:
            self.fields[campo].widget.attrs['class'] = 'form-control'
            self.fields[campo].widget.attrs['id'] = 'input'+campo.capitalize()
        
        self.fields['first_name'].widget.attrs['autofocus'] = 'autofocus'

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'phone']
        error_messages = {
            'username':{
                'unique': 'Esse usuário já existe.',
            },
            'email':{
                'unique': 'Esse email já existe.'
            }
        }

class LoginForm(forms.Form):
    widgets = {
        'email': forms.TextInput(attrs={
            'class':'form-control',
            'placeholder':'Email address',
            'name': 'username',
            'autofocus':True,
        }),
        'password': forms.PasswordInput(attrs={
            'class':'form-control',
            'placeholder':'Senha',
            'name': 'password',
        }),
    }

    inputEmail = forms.CharField(label="User/Email", widget=widgets['email'])
    inputPassword = forms.CharField(label="Senha", widget=widgets['password'])
    

class UpdateProfile(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name', 'phone')
        error_messages = {
            'username':{
                'unique': 'Esse usuário já existe.',
            },
            'email':{
                'unique': 'Esse email já existe.'
            }
        }

        
    def clean_email(self):
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')

        if email and CustomUser.objects.filter(email=email).exclude(username=self.instance.username).count():
            raise forms.ValidationError('This email address is already in use. Please supply a different email address.')

        return email

bet/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeForm
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.db.models import Count
from django.contrib.sites.shortcuts import get_current_site
from django.utils.functional import SimpleLazyObject
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from urllib.parse import urlencode

from collections import Counter
from datetime import datetime
import json
import re

from simple_email_confirmation.models import EmailAddress
from pagseguro.api import PagSeguroApiTransparent

from .forms import CreateUserForm, LoginForm, UpdateProfile
from .models import *

CONTACT_EMAIL_MESSAGE = "Email enviado por {}, através do email {}\n\n{}"

def index(request):
    depoimentos = Depoimentos.objects.all()
    products = Produtos.objects.all()
    faq_tema = FaqTemas.objects.all().first()

    context =  {
        'site': request.site,
        'faq_tema': faq_tema,
        'depoimentos': depoimentos,
        'products': products,
        'resended': request.GET.get('resended'),
        'succes_message': True,
    }

    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = CONTACT_EMAIL_MESSAGE.format(name, email, request.POST.get('message'))
        
        send_mail(subject=subject, message=message, from_email=email, recipient_list=[settings.EMAIL_HOST_USER])
        messages.success(request, 'Email de contato enviado.')

    elif request.user.is_authenticated and bool(EmailAddress.objects.filter(user__pk=request.user.pk, confirmed_at=None)):
        if not context['resended']:
            context['success_message'] = False
            for message in messages.get_messages(request):
                if "confirmation_request" in message.tags:
                    return render(request, 'bet/home/index.html', context=context)

            print("MAARAVILAH",messages.get_messages(request))
            messages.warning(request, 'Seu email não está confirmado, por favor confirme acessando link que mandamos em seu email.')
        else:
            context['success_message'] = True
            messages.warning(request, 'Link de confirmação enviado.')

    return render(request, 'bet/home/index.html', context=context)

def faq_view(request, tema_pk):
    perguntas = Faq.objects.filter(tema__pk=tema_pk).values('pergunta', 'resposta')
    temas = FaqTemas.objects.annotate(number_of_questions=Count('faq'))

    return render(request, 'bet/faq/faq-perguntas.html', {
        'perguntas': perguntas,
        'temas': temas,
        'id': tema_pk,
    })

def login_view(request):
    if request.user.is_authenticated:
        return redirect('bet:index')

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = request.POST.get('inputEmail')
            password = request.POST.get('inputPassword')

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                if not request.GET.get('next'):
                    return redirect('bet:profile', page="infos")
                else:
                    return HttpResponseRedirect(request.GET.get('next'))
            else:
                messages.info(request, "usuário/email ou senha incorretos")

    form = LoginForm(auto_id="%s")
    return render(request, 'bet/accounts/login.html', context={'form':form})

def logout_view(request):
    logout(request)
    return redirect('bet:index')

def register(request):
    if request.user.is_authenticated:
        return redirect('bet:index')

    form = CreateUserForm()
    
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            
            send_confirmation_link(user, request.site)

            return redirect('bet:login')
        else:
            for msgs in form.errors.as_data().values():
                for msg in msgs:
                    messages.error(request, *msg)

    return render(request, 'bet/accounts/register.html', {'form': form})

def change_pass(request):
    form = PasswordChangeForm(user=request.user, data=request.POST)

    if form.is_valid():
        form.save()
        update_session_auth_hash(request, form.user)
        messages.success(request,"Senha alterada.")
    else:
        errors = json.loads(form.errors.as_json())
        
        for error_field, error_list in errors.items():
            code = error_list[0]['code']
            if code == 'password_mismatch':
                messages.error(request,'Senhas não coincidem')
            elif code == 'password_incorrect':
                messages.error(request,'Senha atual incorreta.')
            else:
                messages.error(request,error_list[0]['message'])

def change_infos(request):
    old_email = request.user.email
    form = UpdateProfile(request.POST, instance=request.user)

    if form.is_valid():
        form.save()

        if old_email != request.POST.get('email'):
            EmailAddress.objects.filter(user=request.user).delete()
            send_confirmation_link(request.user, request.site)

            messages.success(request, "Alterado com sucesso! Confirme seu email por meio do link que mandamos.")
        else:
            messages.success(request, "Alterado com sucesso!")

    else:
        errors = json.loads(form.errors.as_json())
        print(errors)
        for error in errors.values():
            message = error[0]['message']
            if 'This email address is already in use' in message:
                message = "Esse email já está cadastrado."

            messages.error(request, message)

@login_required(login_url="bet:login")
def profile_view(request, page):
    context = {
        'page': page,
        'has_vip': UserProdutos.objects.filter(user=request.user, vip_expiration__gte=datetime.now()).count(),
    }
    
    if page == "infos":
        context['form'] = UpdateProfile()

    elif page == "planos":
        try:
            context['expiration'] = UserProdutos.objects.filter(user=request.user).order_by('vip_expiration').last().vip_expiration.date()
        except AttributeError:
            context['expiration'] = "Não contratado"

    if request.method == 'POST':
        if page == "password":
            change_pass(request)

        elif page == "infos":
            change_infos(request)
            return redirect("bet:profile", page="infos")

    return render(request, "bet/accounts/profile-%s.html"%(page), context=context)

@login_required(login_url="bet:login")
def request_vip(request):
    purchase = UserProdutos.objects.filter(user=request.user, vip_expiration__gte=datetime.now(), status="pago").order_by('vip_expiration').last()

    if purchase:
        vip_req = VipRequest.objects.requestVip(purchase)
        vip_req.added = False
        vip_req.save()

        messages.success(request, "Já solicitamos a sua entrada ao grupo, iremos verificar os dados.")

    else:
        messages.warning(request, "Você não possui esse plano. Gostaria de contratar? ")

    return redirect("bet:profile", page="planos")

@login_required(login_url="bet:login")
def request_curso(request):
    has_course = UserProdutos.objects.filter(user=request.user, produto__pk=2, status="pago").count()

    if has_course:
        message = "Olá {}, aqui está o link do nosso curso.\n\n{}\n\nTenha um bom aprendizado!\n atenciosamente hackeandoabanca.".format(request.user.first_name,"https://google.com")
        send_mail(subject="Solicitação do link do curso", message=message, from_email=settings.EMAIL_HOST_USER, recipient_list=[request.user.email])

        messages.success(request, "Enviamos o link para o seu email.")

    else:
        messages.warning(request, "Você não possui esse plano. Gostaria de contratar? ")

    return redirect("bet:profile", page="planos")

@login_required(login_url="bet:login")
def pagamento_page(request, product_pk):
    
    if not bool(EmailAddress.objects.filter(user__pk=request.user.pk, confirmed_at=None)):
        produto = Produtos.objects.get(pk=product_pk)

        if request.method == 'POST':
            data = UserProdutos.objects.create_checkout(request, produto)
            print("DATA")
            print(data)
            if data['status_code'] != 200:
                messages.warning(request, "Existem campos inválidos. Por favor tente novamente")
                return redirect("bet:pagamento", product_pk=product_pk)
            try:
                link_boleto = data['transaction']['paymentLink']
                message = "Olá {}, aqui está o boleto para o pagamento do plano.\nAgradecemos sua compra. {}".format(
                    request.user.first_name, request.site.name)
                send_mail("Boleto de pagamento", message, from_email=settings.EMAIL_HOST_USER, recipient_list=[request.user.email,])

            except KeyError:
                pass


bet/templates/bet/home/contato.html
{% load static %}

<section id="contato">
    <div class="contact1">
        <div class="container-contact1">
            <div>
                <img id="contact-img" src="{% static "images/img-01.png" %}" alt="IMG">
            </div>

            <form class="contact1-form validate-form" method="POST">
                {% csrf_token %}
                <span class="contact1-form-title">
                    Entre em contato
                </span>

                <div class="wrap-input1 validate-input" data-validate="Name is required">
                    <input class="input1" type="text" name="name" placeholder="Nome">
                    <span class="shadow-input1"></span>
                </div>

                <div class="wrap-input1 validate-input" data-validate="Valid email is required: ex@abc.xyz">
                    <input class="input1" type="text" name="email" placeholder="Email">
                    <span class="shadow-input1"></span>
                </div>

                <div class="wrap-input1 validate-input" data-validate="Subject is required">
                    <input class="input1" type="text" name="subject" placeholder="Assunto">
                    <span class="shadow-input1"></span>
                </div>

                <div class="wrap-input1 validate-input" data-validate="Message is required">
                    <textarea class="input1" name="message" placeholder="Mensagem"></textarea>
                    <span class="shadow-input1"></span>
                </div>

                <div class="container-contact1-form-btn">
                    <button class="contact1-form-btn" type="submit">
                        <span>
                            Enviar Email
                            <i class="fa fa-long-arrow-right" aria-hidden="true"></i>
                        </span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</section>

bet/templates/bet/home/depoimentos.html
{% load static %}

<section id="depoimentos">
    <div class="container text-center">
        <h2 class="font-weight-light mb-5">Depoimentos</h2>
        <div class="row mx-5 px-5 my-auto">
            <div id="depoimentosCarousel" class="col carousel slide w-100" data-ride="carousel">
                <div class="carousel-inner w-100" role="listbox">
                    {% for depoimento in depoimentos %}
                        {% if forloop.first %}
                        <div class="carousel-item active">
                        {% else %}
                        <div class="carousel-item">
                        {% endif %}
                            <div class="col-md-2">
                                <button type="button" data-toggle="modal" data-target="#modal{{forloop.counter}}">
                                    <img src="{{depoimento.foto.url}}" class="rounded-circle rounded-corners-gradient-borders" alt="..." >
                                </button>
                            </div>
                        </div>
                    {% endfor %}
                    
                    <!-- <div class="carousel-item">
                        <div class="col-md-2">
                            <img src="{% static "images/perfil.jpg" %}" class="rounded-circle rounded-corners-gradient-borders" alt="..." >
                        </div>
                    </div> -->
                </div>
                <a class="carousel-control-prev w-auto" href="#depoimentosCarousel" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon bg-dark border border-dark rounded-circle"
                        aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next w-auto" href="#depoimentosCarousel" role="button" data-slide="next">
                    <span class="carousel-control-next-icon bg-dark border border-dark rounded-circle"
                        aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
    <div id="modals">
        {% for depoimento in depoimentos %}
        <div class="modal fade" id="modal{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" value="teste domodal">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="embed-responsive embed-responsive-4by3">
                        <iframe class="embed-responsive-item" src="{{depoimento.video_link}}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
            </div>
        </div>
        {% endfor %}
        <!-- <div class="modal fade" id="exampleModal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" value="teste domodal">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="embed-responsive embed-responsive-4by3">
                        <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/Sgg0io-gfaw" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
            </div>
        </div> -->
    </div>
  </section>

bet/templates/bet/home/index.html
{% extends "bet/base.html" %} 
{% load static %} 

{% block css_links %}
<link rel="stylesheet" href="{% static "css/style.css" %}"> 
<link rel="stylesheet" href="{% static "css/contato.css" %}"> 
{% endblock %} 

{% block content %}

<section id="banner">
  <div class="container">
    <div class="row">
      <div class="col">
        <!-- <h1 class="text-center">Hackeando a Banca</h1>
        <p class="lead text-center">
          texte employé dans la composition et la mise en page
        </p> -->
        <div class="embed-responsive embed-responsive-16by9">
          <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/xIHNgyXNvLQ" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="infos" class="shadow-lg">
  <div class="container">
    <div id="left-info" class="row">
      <div class="col-8">
        <h4>Curso</h4>
        <br />
        <p class="lead text-justify">
          On sait depuis longtemps que travailler avec du texte lisible et
          contenant du sens est source de distractions, et empêche de se
          concentrer sur la mise en page elle-même.
        </p>
      </div>
      <div class="col text-right">
        <img class="img-fluid" src="{% static "images/video-play-4-128.ico" %}"
        alt="">
      </div>
    </div>
  </div>

  <hr />

  <div class="container">
    <div id="right-info" class="row">
      <div class="col">
        <img class="img-fluid" src="{% static "images/diamond-128.ico" %}"
        alt="">
      </div>
      <div class="col-8">
        <h4>VIP</h4>
        <br />
        <p class="lead text-justify">
          On sait depuis longtemps que travailler avec du texte lisible et
          contenant du sens est source de distractions, et empêche de se
          concentrer sur la mise en page elle-même.
        </p>
      </div>
    </div>
  </div>
</section>

{% include 'bet/home/planos.html' %}

{% include 'bet/home/depoimentos.html' %}

<div id="faq-gap"></div>

{% include 'bet/home/contato.html' %}

<div id="footer-gap"></div>

<footer class="d-flex flex-row font-small">

  <span class="mx-auto pb-2">© 2020 Copyright:<a href="https://{{site}}/"> {{site}}</a></span>

</footer>

{% include 'bet/home/navbar.html' %}

{% endblock %}
{% block scripts %}
<script src="{% static "js/home.js" %}"></script>
{% endblock %}

bet/templates/bet/home/navbar.html
{% load static %}

    <section class="nav fixed-top">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
                <a class="ml-5 pl-5 navbar-brand" onclick="active_link(this)" href="#">
                    <img src="{% static "images/cards-32.ico" %}" class="d-inline-block align-top" alt="" loading="lazy">
                    <span id="brand-title">Hackeando <span class="span-brand">a Banca</span></span>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" onclick="active_link(this)" href="#">Home</a>
                    <a class="nav-item nav-link ml-3" onclick="active_link(this)" href="#infos">Infos</a>
                    <a class="nav-item nav-link ml-3" onclick="active_link(this)" href="#planos">Planos</a>
                    <a class="nav-item nav-link ml-3" onclick="active_link(this)" href="#contato">Contato</a>
                    <a class="nav-item nav-link ml-3" href="{% url "bet:faq" tema_pk=faq_tema.pk%}">Faq</a>
                    {% if user.is_authenticated %}
                    <li class="nav-item ml-4 dropdown">
                        <a id="profile-link" class="nav-link dropdown-toggle user-icon" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span style="font-size: 25px;">
                                <i class="fas fa-user-circle"><span style="margin-left: 5px; font-size: 16px;">Perfil</span></i>
                            </span>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url "bet:profile" page="infos" %}">Minha conta</a>
                            <a class="dropdown-item" href="{% url "bet:logout" %}">Sair</a>
                        </div>
                    </li>
                    {% else %}
                    <a id="profile-link" href="{% url "bet:login" %}" class="nav-item nav-link user-icon ml-4">
                        <span style="font-size: 25px;"><i class="fas fa-user-circle"><span style="margin-left: 5px; font-size: 16px; text-decoration:underline">Login</span></i></span>
                    </a>
                    {% endif %}
                </div>
                </div>
            </nav>
            
            {% for message in messages %}
                <div class="text-center alert {% if success_message == False %}alert-danger{% else %}alert-success{% endif %} alert-dismissible fade show" role="alert">
                    {{message}} {% if success_message == False %}<a href="{% url "bet:resend-confirmation" %}" class="alert-link">Resend link</a>{% endif %}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        </div>
    </section>

bet/templates/bet/home/planos.html
{% load static %}
<section id="planos">
    <div class="container">
        <div class="row">
            <div class="col">
                <h3 class="text-center">Planos</h3>
                <p class="lead text-center">Adquira um dos nossos planos</p>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col"></div>
            <div class="col-6 rounded">
                <a id="telegram" href="#" class="btn btn-dark btn-block mb-5 text-left">
                    <span style="font-size: 28px;">
                        <i class="fab fa-telegram ml-5 pl-1"></i>
                        <span style="font-size: 20px;" class="ml-2 pl-3">
                        Entre em nosso canal do telegram
                        </span>
                    </span>
                </a>
            </div>
            <div class="col"></div>
        </div>
        <br>
        <div class="row">
            <div id="plan" class="col">
                <div class="card-deck text-center">
                    {% for product in products %}
                    <div class="card shadow-lg">
                        <div class="c-header">
                            <h4 class="my-0 font-weight-normal">{{product.nome}}</h4>
                        </div>
                        <div class="card-body d-flex flex-column">
                            <h1 class="card-title pricing-card-title">R$ {{product.preco_text}}</h1>
                            <ul class="list-unstyled mt-3 mb-4">
                                {{product.descricao|linebreaks}}
                            </ul>
                            <a id="buy" href="{% url "bet:pagamento" product.id %}" class="align-self-end btn btn-lg btn-outline-dark px-4 mx-auto mt-auto">
                                Comprar
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>

